server:
  port: 80

spring:
  http:
    encoding:
      force: true
      charset: utf-8
  # 定义数据库连接语句
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sqd?serverTimezone=UTC
    username: root
    password: zhy010919
  # thymeleaf 模板引擎配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  # 文件上传大小设置
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

# mybatis 扫描位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haoduor.graduation.model

snow:
  data-center: 1
  worker: 1

# 分页插件 配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

file:
  save-path: E:\graduation_management\file\save\
  tmp-path: E:\graduation_management\file\tmp\

admin:
  code: asdasd
